<?php
$title = 'Добавить категорию';
$this->headTitle($title);

?>
    <h1><?=$this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('zfcadmin/news/categories', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('security'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('visible'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();