<?php

$title = 'Изменение категории';
$this->headTitle($title);
?>
<?=$this->showMessages();?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?=$this->url('zfcadmin/news/categories', array('action'=>'index'));?>">К списку новостей...</a>
</p>
<?php
$form = $this->form;

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('security'));
echo $this->formRow($form->get('name'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();