<?
    $title = "Категории";
    $this->headTitle($title); 
?>
<?=$this->showMessages();?>
<h1><?=$title;?></h1>
<p>
    <a href="<?=$this->url('zfcadmin/news/categories', array('action'=>'add'));?>">Добавить категорию</a>
</p>
<table class='table'>
    <tr><th>Название</th><th>Краткий url</th><th>Действия</th></tr>
    <? if(0 == count($this->categories)) : ?>
        <tr><td colspan="2">Категорий еще нет, вы можете <a href="<?=$this->url('zfcadmin/news/categories', array('action'=>'add'));?>">добавить новую</a></td></tr>
    <? else: ?>
        <? foreach($this->categories as $category) : ?>
            <tr>
                <td><?=$category->getName();?></td>
                <td><a href="<?=$this->url('news/category', array('category'=>$category->getUrl()));?>">/<?=$category->getUrl();?></a></td>
                <td>
                    <a href="<?=$this->url('zfcadmin/news/categories', array('action'=>'edit', 'id' => $category->getId()));?>">изменить</a>,
                    <a href="<?=$this->url('zfcadmin/news/categories', array('action'=>'delete', 'id' => $category->getId()));?>">удалить</a>
                </td>
            </tr>
        <? endforeach; ?>
    <? endif; ?>
</table>

<? if($this->categories->count() > 1): ?>
    <div class="centered">
        <?=$this->paginationControl(
            $this->categories,
            'Sliding',
            'pagination_control',
            array('route' => 'zfcadmin/news/categories/pagination')
        )?>
    </div>
<? endif; ?>