<div>
    <? if(0 == count($this->news)) : ?>
        <h2>Новостей нет</h2>
    <? else: ?>
        <? foreach($this->news as $item) : ?>
            <div>
                <a href="<?=$this->url('news', array('action'=>'full', 'id' => $item['id']));?>"><?=$item['title'];?></a>
                [ <?=date('d.m.Y в H:i', $item['created']); ?>],
                <a href="<?=$this->url('news', array('action'=>'edit', 'id' => $item['id']));?>">edit</a>,
                <a href="<?=$this->url('news', array('action'=>'delete', 'id' => $item['id']));?>">delete</a>
            </div>
        <? endforeach; ?>
    <? endif; ?>
</div>