<?php

$title = 'Добавление новости';
$this->headTitle($title);
?>
<?=$this->showMessages();?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?=$this->url('zfcadmin/news');?>">К списку новостей...</a>
</p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('zfcadmin/news/add'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('security'));
echo $this->formRow($form->get('category'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('text'));
echo $this->formRow($form->get('visible'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();