<?
    $title = $this->categoryName ?: "Список новостей";

    $this->headTitle($title); 
?>
    <? echo $this->categoryName ?  "<h1>Категория: $this->categoryName</h1>" : "<h1>Список новостей</h1>"; ?>
<? if($this->news): ?>
    <? foreach($this->news as $item): ?>
        <div>
            <label>Заголовок</label>
            <a href="<?=$this->url('news/full', array('id' => $item->getId()));?>"><?=$item->getTitle()?></a>
        </div>
        <div>
            <label>Категория</label>
            <a href="<?=$this->url('news/category', array('category' => $item->getCategoryUrl()));?>"><?=$item->getCategoryName()?></a>
        </div>
        <div>
            <label>Создано</label>
            <?=date('d.m.Y в H:i', $item->getCreated());?>
        </div>
        <div>
            <label>Автор</label>
            <?=$item->getUserName();?>
        </div>
        <div>
            <label>Полный текст новости</label>
            <?=$item->getText();?>
        </div>
        <hr />
    <? endforeach; ?>
<? else: ?>
    <div>Нет новостей для отображения</div>
<? endif; ?>