<? 
    $title = "Список новостей";
    $this->headTitle($title); 
?>
<?=$this->showMessages();?>
<h1><?=$title;?></h1>
<p>
    <a href="<?=$this->url('zfcadmin/news/add', array('action'=>'add'));?>">Добавить новость</a>
</p>
<table class='table'>
    <? if(0 == count($this->news)) : ?>
        <tr><td colspan="6">Новостей нет. <a href="">Добавить новость</a></td></tr>
    <? else: ?>
        <tr><th>Название</th><th>Категория</th><th>Добавил</th><th>Статус</th><th>Добавлено</th><th>Действия</th></tr>
        <? foreach($this->news as $item) : ?>
            <tr>
                <td>
                    <a href="<?=$this->url('news', array('action'=>'full', 'id' => $item['id']));?>"><?=$item['title'];?></a> 
                </td>
                <td>
                    <?=$item['category'];?>
                </td>
                <td>
                    <?=$item['user'];?>
                </td>
                <td>
                     <? if(0 == $item['visible']): ?>Скрыта<? else: ?>Показана<? endif ?>
                </td>
                <td>
                    <?=date('d.m.Y в H:i', $item['created']); ?>
                </td>
                <td>
                    <a href="<?=$this->url('zfcadmin/news/edit', array('id' => $item['id']));?>">изменить</a>,
                    <a href="<?=$this->url('zfcadmin/news/delete', array('id' => $item['id']));?>">удалить</a>
                </td>
            </tr>
        <? endforeach; ?>
    <? endif; ?>
</table>